name: pip_install_jack
on: [pull_request, push]
jobs:
  pip_install_jack:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11", "pypy3.9"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install --upgrade pip wheel
      - run: pip install jack
      # - run: pip install .
